com:
  mqtt:
    hosts: 
      - tcp://10.135.78.20:1883
      - tcp://10.135.78.23:1883
      - tcp://10.135.78.54:1883
    topics: 
      - tsp/tbox/#
    username: user1
    password: pass1
    connectionTimeout: 10
    completionTimeout: 30000
    keepalive: 20
    clientIdSend: mqtt-client4-send-001
    clientIdRecive: mqtt-client4-recive-001
    defaultTopic: defaultTopic
    async: true
    cleanSession: true